apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: blog-posts-bundle
resources:
  - ./categories/ckad-preparation.yaml
  - ./posts/20250501-introduction.yaml
  - ./posts/20251018-ckad-testing-networkpolicy.yaml
  - ./posts/20251019-ckad-what-is-kubernetes.yaml
  - ./posts/20251020-ckad-build-a-container-image.yaml
  - ./posts/20251021-ckad-choose-workload-resource.yaml
  - ./posts/20251022-ckad-understanding-multi-container-pods.yaml
  - ./posts/20251023-ckad-utilize-persistent-ephemeral-volumes.yaml
  - ./posts/20251104-talos-replace-flannel-with-calico.yaml
  - ./posts/20251121-ckad-implement-blue-green-canary-deployments.yaml
  - ./posts/20251124-ckad-understanding-deployments-rolling-updates.yaml
