apiVersion: blog.supaahiro.io/v1alpha1
kind: BlogPost
metadata:
  name: 20260131-ckad-monitoring-kubernetes-applications-with-built-in-cli-tools
spec:
  id: 20260131-ckad-monitoring-kubernetes-applications-with-built-in-cli-tools
  title: CKAD Preparation â€” Monitoring Kubernetes Applications with Built-in CLI Tools
  previewImage: https://supaahiro.github.io/schwifty-lab/blog-posts/20260131-ckad/article.webp
  summary: Master Kubernetes application monitoring using built-in CLI tools. Learn kubectl get, describe, events and top to effectively observe and monitor your applications in real-time.
  contentUrl: https://raw.githubusercontent.com/SupaaHiro/schwifty-lab/refs/heads/master/blog-posts/20260131-ckad/article_EN.md
  publishedOn: "2026-01-31T00:00:00Z"
  author: Hiro
  categoryId: ckad-preparation
  relatedPostsIds: []
status:
  published: true
  indexed: true
