---

- name: Power off the cluster nodes

  vars_files:
    - ../vault/vault-keyring.yaml

  hosts:
    - cluster

  tasks:
    - name: Power Off OVA
      ansible.builtin.include_tasks: ../tasks/power_off_ova.yml
...
