apiVersion: apps/v1
kind: Deployment
metadata:
  name: green-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo
      version: green
  template:
    metadata:
      labels:
        app: demo
        version: green
    spec:
      volumes:
        - name: web-assets
          configMap:
            name: web-assets
            items:
              - key: green.html
                path: index.html
      containers:
        - name: app
          image: nginx:1.29.3-perl
          env:
            - name: COLOR
              value: "green"
          volumeMounts:
            - name: web-assets
              mountPath: "/usr/share/nginx/html"
              readOnly: true
